apiVersion: batch/v1
kind: Job
metadata:
  name: condaenv-exporter
spec:
  template:
    spec:
      containers:
      - name: condaenv-exporter
        image: kisti.rdp/dataon.kr/condaenv-exporter:0.3.4
        volumeMounts:
        - name: conda-pubenvs
          mountPath: /opt/conda/pubenvs
        - name: conda-usrenvs
          mountPath: /opt/conda/usrenvs
        - name: workspace
          mountPath: /mnt/workspace
        - name: lustre
          mountPath: /mnt/share/lustre
        env:
        - name: EXPORTMODE
          value: $EXPORTMODE
        - name: NB_USER
          value: $NB_USER
        - name: NB_UID
          value: $NB_UID
        - name: NB_GID
          value: $NB_GID
        - name: SRCENVNAME
          value: $SRCENVNAME
        - name: DSTENVNAME
          value: $DSTENVNAME
        - name: WETRUNARGS
          value: $WETRUNARGS
        - name: LOGFILE
          value: $WETRUNLOGF
        - name: LAP
          value: "FALSE"
        - name: CONDA_DEFAULT_THREADS
          value: "12"
      volumes:
      - name: conda-pubenvs
        hostPath:
          path: /mnt/share/lustre/Canvas/pubs/envs
          type: Directory
      - name: conda-usrenvs
        hostPath:
          path: /mnt/share/lustre/user/$SU_USR_HOME/.usrenvs
          type: Directory
      - name: workspace
        hostPath:
          path: /mnt/share/lustre/user/$SU_USR_HOME
          type: Directory
      - name: lustre
        hostPath:
          path: /mnt/share/lustre
          type: Directory
      restartPolicy: Never
